### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Johann-S** [nirtz89/crumbsjs#16]
Hi,

After reading your source code you use a lot of ES6 features (that's great), but your plugin can be usefull for people which target IE 11 for example and it won't work.

So it would be interesting to add Rollup with Babel to transpile your source code in ES5 if you want.

Or I think it should be interesting to specify precisely which browsers works with your plugin 👍

**Comment by nirtz89** [comment]
Using `babel` is in the works and will probably be released in the next version 👍

**Comment by Johann-S** [comment]
if you need any help, do not hesitate 👍

**Comment by nirtz89** [comment]
Feel free to help, the gulp file needs to be updated with a dist with `babel` and the `gulp-babel` itself needs to be installed and added as a `dev-dependency`

**Comment by Johann-S** [comment]
Rollup or Webpack should be added too, to define how you want to export your plugin (UMD, ESM, IIFE).
UMD is between ESM and IIFE and allow your users to use your plugin in a bundler or directly in a browsers

**Comment by nirtz89** [comment]
Closing this.
Library now supports ES5, thanks to @Johann-S 👍
