### ISSUE TITLE
Can't get bundlephobia.com to display the bundle size of crumbsjs

### ISSUE THREAD

**Issue by cherouvim** [nirtz89/crumbsjs#5]
https://bundlephobia.com/result?p=crumbsjs shows:

> EntryPointError
> We could not guess a valid entry point for this package. Perhaps the author hasn't specified one in its package.json ?

**Comment by Johann-S** [comment]
Yep that's because in the package.json the `main` field is equal to `index.js` when it should be equal to `dist/crumbs.js`

see: https://github.com/nirtz89/crumbsjs/blob/master/package.json#L5
